softmaterialslab/nanoconfinement-md

- rappture/tool.xml
- src/NanoconfinementMd.cpp
- src/NanoconfinementMd.h
- src/functions.cpp
- src/functions.h
- src/input_config.cfg
- src/interface.cpp
- src/md.cpp
- src/utility.h
> Changed the IO file paths and boost inputs

- src/NanoconfinementMd.cpp
@smarru and @jadhao 
I have fixed the issue.
Please accept this.
Thanks
> Commented one return statement

- _config.yml
- src/Makefile
* Adding a documentation theme 
* Merged with Vikram's makefile sent by email
> Documentation theme

- rappture/nanoconfinement-wrapper.py
- rappture/tool.xml
Combined +/- density plots are added.
> Combined +/- density plots are added

- src/NanoconfinementMd.cpp
- src/NanoconfinementMd.h
- src/control.h
- src/functions.h
- src/md.cpp
@smarru @kadupitiya please check if things run fine on either platforms with this change.
i think verbose is natural in mdremote, so i made it a member of the control class that controls what simulation we run
> made verbose member of CONTROL class which sets the mdremote

- rappture/nanoconfinement-wrapper.py
- src/Makefile
- src/NanoconfinementMd.cpp
- src/control.h
- src/databin.h
- src/energies.h
- src/forces.h
- src/functions.cpp
- src/functions.h
- src/interface.cpp
- src/interface.h
- src/md.cpp
- src/mdenergies.cpp
- src/mdforces.cpp
- src/particle.h
- src/thermostat.h
- src/utility.h
- src/vector3d.h
- src/vertex.h
I have changed the python wrapper and Makefile.
> Rappturized MPI version

- rappture/nanoconfinement-wrapper.py
- scripts/README
- src/NanoconfinementMd.cpp
@jadhao : Please approve this.
> Changes by Vikram-V2

- docs/index.md
- docs/nanohub_deployment.md
> Changes to documentation

- rappture/nanoconfinement-wrapper.py
> wrapper script changed.

- src/NanoconfinementMd.cpp
- src/utility.h
@jadhao
I made unitlength, unittime, scalefactor as global variables. The energy results are the same as the example file in Github.
> Make unitlength, unittime, scalefactor global variables

- rappture/nanoconfinement-wrapper.py
@jadhao : Please approve this.
Thanks
> Computing cluster updated

- middleware/invoke
- rappture/nanoconfinement-wrapper.py
@jadhao : Please approve this.
Thanks
> More changes for new update

- rappture/nanoconfinement-wrapper.py
@jadhao : Please accept this.
Hopefully, this would be final PR.
> More changes

- src/NanoconfinementMd.cpp
- src/interface.cpp
@jadhao
The "interface.cpp" and " NanoconfinementMd.cpp" are changed. For all different values of concentration there are 676 mesh point on each interface.
> Change Interface

- src/interface.cpp
@jadhao
I changed the location of walls in movie file. I checked the results of energy for modified and the original codes. The are the same.
> Change the Location of Walls

- src/NanoconfinementMd.cpp
- src/databin.h
- src/functions.cpp
- src/functions.h
- src/md.cpp
- src/utility.h
@jadhao:
PR for contact density binning.
> Contact density bins added

- src/mdenergies.cpp
- src/mdforces.cpp
@jadhao and @kadupitiya:
The Dummy is back. The no dummy lines are comment out and I checked the energy profile with energy results in example file.
> Dummy Back

- Makefile
- src/interface.cpp
- src/mdenergies.cpp
@jadhao and @kadupitiya 
I changed "INTERFACE::generate_lammps_datafile" function in interface.cpp to generate correct input data for lammps (preprocessing set up).
> preprocessing set up for lammps

- src/NanoconfinementMd.cpp
- src/NanoconfinementMd.h
- src/functions.cpp
- src/functions.h
- src/md.cpp
@jadhao 
@kadupitiya 
PR from my fork based on the latest code.
> -J true for density from lammps

- middleware/invoke
- src/NanoconfinementMd.cpp
- src/functions.cpp
@jadhao and @nasimanousheh: Minor print statement adjustments.
> Minor print statement adjustments

- bin/infiles/in.lammps.template
- src/NanoconfinementMd.cpp
@jadhao: Please check.
LAMMPS script changed.
> LAMMPS script changed

- bin/infiles/in.lammps.template
- src/NanoconfinementMd.cpp
- src/functions.cpp
- src/functions.h
- src/interface.cpp
- src/interface.h
@jadhao 
@kadupitiya 
I send you output (for 1ns) after modifications by email.
> Asymmetry Changes

- src/interface.cpp
@jadhao , @kadupitiya 
The ion valency issue is corrected in interface.cpp
> fix ion valency

- bin/infiles/in.lammps.template
- src/NanoconfinementMd.cpp
- src/interface.cpp
- src/interface.h
- src/utility.h
@jadhao 
@kadupitiya 
In LAMMPS, the value of charge density on surface is fixed (around -0.01 C.m-2). In next step,  we will ask user to choose the charge density between zero to specific value.
> Define charge on surface in LAMMPS

- bin/infiles/in.lammps.template
- src/NanoconfinementMd.cpp
- src/interface.cpp
- src/interface.h
@jadhao and @kadupitiya 
I defined the bigger_ion_diameter and smaller_ion_diameter according to their sizes.
> define bigger and smaller ion salt

- src/mdforces.cpp
@jadhao and @kadupitiya 
I already added "if condition" in mdenergy.cpp to not calculate the ion-walls electrostatic interactions if there is no charge on the walls. This increased the speed of simulation. I forgot to add the same condition for mdforce.cpp. This would diffidently increase the speed of simulation more for uncharged case, without changing the results.
> increase the speed for nochaged surface

- Makefile
- src/Makefile
- src/NanoconfinementMd.cpp
- src/NanoconfinementMd.h
- src/functions.cpp
- src/functions.h
- src/md.cpp
@jadhao and @kadupitiya 
New functions to create screening factor and net charge density profiles are added.
> Screening factor

- src/NanoconfinementMd.cpp
@kadupitiya and @jadhao 
NanoconfinementMd.cpp is updated. The correct value of bin_width is defined to calculate screening factor.
> exact value of bin_width

- scripts/nanoconfinement.pbs
- src/Makefile
@jadhao: Please check this.
Including Bigred3 lib updates in configs.
> Including Bigred3 lib updates in configs.

- src/NanoconfinementMd.cpp
@jadhao: Please check and approve.
> electroneutral-issue fixed

- bin/infiles/in.lammps.chargedsurface.template
- bin/infiles/in.lammps.unchargedsurface.template
- src/NanoconfinementMd.cpp
- src/functions.cpp
- src/functions.h
@jadhao: Please check and approve.
> Suggested changes

- middleware/invoke
@jadhao: NanoHUB needs one change.
> updates with new ML surrogate

- bin/nanoconfinement-frontend.ipynb
@jadhao: Can you please approve?
> Bux fix for input exact value for uq
